db:
    image: mysql
    container_name: mysql_db
    environment:
        MYSQL_ROOT_PASSWORD: sesame
        MYSQL_DATABASE: fireService
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
        - "33333:3306"
    volumes:
        - ./FireServiceDatabase.sql:/docker-entrypoint-initdb.d/FireServiceDatabase.sql
       